var languageNames = {
"en-US": "English (USA)",
"sq": "Albanian",
"am": "Amharic",
"ar": "Arabic",
"ast": "Asturian",
"bn": "Bengali",
"bn-IN": "Bengali (India)",
"bs": "Bosnian",
"bg": "Bulgarian",
"ca": "Catalan",
"ca-valencia": "Catalan (Valencia)",
"zh-CN": "Chinese (Simplified)",
"zh-TW": "Chinese (Traditional)",
"hr": "Croatian",
"cs": "Czech",
"da": "Danish",
"nl": "Dutch",
"dz": "Dzongkha",
"en-GB": "English (UK)",
"en-ZA": "English (SA)",
"eo": "Esperanto",
"et": "Estonian",
"eu": "Basque",
"fi": "Finnish",
"fr": "French",
"gl": "Galician",
"ka": "Georgian",
"de": "German",
"el": "Greek",
"gu": "Gujarati",
"he": "Hebrew",
"hi": "Hindi",
"hu": "Hungarian",
"id": "Indonesian",
"is": "Icelandic",
"it": "Italian",
"ja": "Japanese",
"km": "Khmer",
"ko": "Korean",
"lo": "Lao",
"lv": "Latvian",
"lt": "Lithuanian",
"mk": "Macedonian",
"ne": "Nepali",
"nn": "Norwegian Nynorsk",
"nb": "Norwegian Bokmål",
"om": "Oromo",
"pl": "Polish",
"pt": "Portuguese",
"pt-BR": "Portuguese (Brazil)",
"ro": "Romanian",
"ru": "Russian",
"sid": "Sidama",
"si": "Sinhala",
"sk": "Slovak",
"sl": "Slovenian",
"dsb": "Sorbian (Lower)",
"hsb": "Sorbian (Upper)",
"es": "Spanish",
"sv": "Swedish",
"tg": "Tajik",
"ta": "Tamil",
"bo": "Tibetan",
"tl": "Tagalog",
"tr": "Turkish",
"ug": "Uyghur",
"uk": "Ukrainian",
"vi": "Vietnamese",
};
